import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    tutorialSidebar: [
        'installation',
        'introduction',
        'draggable',
        'resizable',
        'gesturable',
        'dropzone',
        'action-options',
        'auto-start',
        'events',
        'modifiers',
        'snapping',
        'restriction',
        'inertia',
        'reflow',
        'tooling',
        'faq',
        'migrating',
    ],
};

export default sidebars;
